### ISSUE TITLE
Time to update the plugin for v2 of Vuetify

### ISSUE THREAD

**Issue by adarshmadrecha** [vuetifyjs/vuetify-vscode#24] opened 2019-07-27 22:16 UTC
#### 1. What is the Component name?
NA

#### 2. What do you want?
Update the plugin to take into consideration recent `v2` update of vuetify

#### 3. What is actually happening?
Currently, the snippets and props suggestions are for `v1`

#### 4. Do you have any recommendation?
Please update the plugin.

**Comment by nekosaur** [comment] 2019-07-29 07:25
This plugin is not currently maintained, and it is very likely it won't be going forward. Please use the vetur plugin instead which offers autocompletion of components and props for 2.0

**Comment by lexxyungcarter** [comment] 2019-08-11 20:35
It would be nice if someone made the PR to be merged to this

**Comment by myleslee** [comment] 2019-08-22 23:46
@nekosaur I'm wondering if there is any special setup to make vetur provide autocompletion of components and props for 2.0? I installed vetur from https://marketplace.visualstudio.com/items?itemName=octref.vetur, but nothing happens when I start typing `vfileinput` or `vbtn` in the VSCode. No autocompletion at all. Thanks!

**Comment by nekosaur** [comment] 2019-08-23 06:47
`vuetify` (or `@nuxtjs/vuetify`) needs to be a direct dependency or dev dependency of your project. Start typing `<v` and they should show up.

**Comment by canhkieu** [comment] 2019-09-30 16:27
My package.json. I installed vetur already. But it's still not autocomplete of comps or props. Could you make a guide.
```
  "dependencies": {
    ...
    "vuetify": "2.0.19",
    ...
  },
```

**Comment by myleslee** [comment] 2019-10-01 23:00
Me too. It doesn't work on Mac so I thought I might have messed up VSCode for installing too many plugins. So I installed VSCode, Vetur and Vuetify on a clean Windows environment, same there, not working. I gave up trying and continued to use the old snippets from vuetify-vscode in conjunction with user-defined vscode snippets.

**Comment by binaryweavers** [comment] 2019-10-03 08:20
Yes it is not working after upgrading to `vuetify@2.1.0`, earlier it was working like a charm

**Comment by nekosaur** [comment] 2019-10-05 08:54
Hmm. I don't know what to tell you. I created a new vue app with `vue create` (default options), then added vuetify with `vue add vuetify` (default options). It installed vuetify version `2.1.1`, and when I opened VS Code it gave me auto-completion immediately.

![vetur](https://user-images.githubusercontent.com/623137/66252663-63ded200-e75e-11e9-92ad-f12cd0104e10.png)

**Comment by binaryweavers** [comment] 2019-10-05 11:23
> Hmm. I don't know what to tell you. I created a new vue app with `vue create` (default options), then added vuetify with `vue add vuetify` (default options). It installed vuetify version `2.1.1`, and when I opened VS Code it gave me auto-completion immediately.
> 
> ![vetur](https://user-images.githubusercontent.com/623137/66252663-63ded200-e75e-11e9-92ad-f12cd0104e10.png)
> 
> edit: remember that you will need to start typing `<` to trigger the auto-completion.

I think it is something to do with the order of folders in `vs-code` workspace.  In my above comment when I updated to `vuetify@2.1.0`  I also (for management purpose) renamed my project directory. I had to remove and re-add that project to `vs-code` workspace. By doing that my `vuetify` project was indexed as second item in workspace json file and same time `vetur` stopped working. 
I just placed the `vuetify` project to first index in json file, everything started working, strange but it is working fine

here is example `.code-workspace` file 
```
{
	"folders": [
		{
			"path": "vuetify-project"
		},
		{
			"path": "api-backend"
		}
	],
	"settings": {
	}
}
```

**Comment by canhkieu** [comment] 2019-10-07 15:43
Confirmed, the problem with .code-workspace in vscode. If we open first project that not vue project or difference folder, It will not autocomplete. The solution is open the vue project first and then add other project later.

**Comment by nekosaur** [comment] 2019-10-07 16:58
Alright, good to have nailed down the cause. This seems to be an upstream problem though. There's this open issue for vetur multi root support which might be relevant?

**Closed** 2019-10-07 16:59 UTC
